# Generated by Django 3.0.7 on 2021-08-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_customerorderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderstatus',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Shipped'), (3, 'Cancelled')], default=1, max_length=1),
        ),
    ]
